// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr0Z0x4f5-ZXKBwCqIl3GP7wZURj2W7wE',
    appId: '1:168462962764:web:f34165e1added78c8ee4e9',
    messagingSenderId: '168462962764',
    projectId: 'flutter-task-64069',
    authDomain: 'flutter-task-64069.firebaseapp.com',
    storageBucket: 'flutter-task-64069.firebasestorage.app',
    measurementId: 'G-CQ5MNX5SZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzTAq9d-CmN4g1RW9_6uRb7JzN5p3JoKc',
    appId: '1:168462962764:android:467c066f0cf75e478ee4e9',
    messagingSenderId: '168462962764',
    projectId: 'flutter-task-64069',
    storageBucket: 'flutter-task-64069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZSrWmdzsqfmFck_WafuaW8q7zZSSTJ9s',
    appId: '1:168462962764:ios:6dcd351d8d433add8ee4e9',
    messagingSenderId: '168462962764',
    projectId: 'flutter-task-64069',
    storageBucket: 'flutter-task-64069.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZSrWmdzsqfmFck_WafuaW8q7zZSSTJ9s',
    appId: '1:168462962764:ios:6dcd351d8d433add8ee4e9',
    messagingSenderId: '168462962764',
    projectId: 'flutter-task-64069',
    storageBucket: 'flutter-task-64069.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr0Z0x4f5-ZXKBwCqIl3GP7wZURj2W7wE',
    appId: '1:168462962764:web:634e2f07eeb2f9908ee4e9',
    messagingSenderId: '168462962764',
    projectId: 'flutter-task-64069',
    authDomain: 'flutter-task-64069.firebaseapp.com',
    storageBucket: 'flutter-task-64069.firebasestorage.app',
    measurementId: 'G-Y480T7JJHD',
  );
}
